name: Hello Grid
favicon: null
layout_spectrum: 0.1138427066616714
typography_spectrum: 0.030499720480293036
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.12181000295095146
  lightness: 0.5804961032699794
  saturation: 0.3297797159757465
  rhythmicContrast: 0.10296208085492253
purpose: []
