name: Hello Grid
favicon: null
layout_spectrum: 1
typography_spectrum: 0.26258
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#186488'
    - '#7ac3e3'
    - '#99a836'
  brandStrength: 0.1875
  lightness: 0.5804961032699794
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
